### ISSUE TITLE
Support for Oracle Linux

### ISSUE THREAD

**Issue by bilalsaeed** [mbrother2/butdr#1]
Please append the following line in detect_os method

|| [[ "${OS}" == "Oracle" ]]

We had an issue installing gdrive on our oracle linux so we modified it accordingly.

**Comment by mbrother2** [comment]
@bilalsaeed 

Is butdr working well on Oracle Linux after you setup?

**Comment by bilalsaeed** [comment]
Yes after I added the Oracle OS condition it's working perfectly fine.

**Comment by mbrother2** [comment]
@bilalsaeed 

I need test more on Oracle Linux to ensure butdr working well. If everything is ok, I will add support Oracle Linux.

**Comment by mbrother2** [comment]
@bilalsaeed 

I tested on Oracle Linux and  it's working well, so I added support Oracle Linux.
