### ISSUE TITLE
Google drive wiki entry is missing

### ISSUE THREAD

**Issue by Mairu** [mbrother2/butdr#2]
When using the script to setup with `bash butdr.bash --setup` and selecting google drive, then the provided link https://github.com/mbrother2/butdr/wiki/Create-own-Google-credential-step-by-step is not usable with the following Github error message: You do not have permission to update this wiki.

**Comment by mbrother2** [comment]
@Mairu 

Thank you for report. I updated butdr wiki from backuptogoogle wiki.
