### ISSUE TITLE
Please add fedora.

### ISSUE THREAD

**Issue by mwarner416** [mbrother2/butdr#5]
Could you please add Fedora as a supported OS.  I've been manually changing code to support it.  Below is /etc/os-release.

NAME=Fedora
VERSION="31 (Server Edition)"
ID=fedora
VERSION_ID=31
VERSION_CODENAME=""
PLATFORM_ID="platform:f31"
PRETTY_NAME="Fedora 31 (Server Edition)"
ANSI_COLOR="0;34"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:31"
HOME_URL="https://fedoraproject.org/"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora/f31/system-administrators-guide/"
SUPPORT_URL="https://fedoraproject.org/wiki/Communicating_and_getting_help"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=31
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=31
PRIVACY_POLICY_URL="https://fedoraproject.org/wiki/Legal:PrivacyPolicy"
VARIANT="Server Edition"
VARIANT_ID=server

**Comment by mbrother2** [comment]
@mwarner416 

Sure! I will test on Fedora. If everything’s ok, I’ll add support it. Please wait.

**Comment by mbrother2** [comment]
@mwarner416 

I added support Fedora. Please try with `butdr.bash --update`

**Comment by mwarner416** [comment]
Works
