### ISSUE TITLE
cannot upload after setup

### ISSUE THREAD

**Issue by bilalsaeed** [mbrother2/butdr#8]
Hi,

I have successfully configured butdr on my Oracle Linux but i am getting the following error when I run cron_backup.bash -v

bash: cron_backup.bash: command not found...

please let me know what I am missing. thanks.

**Comment by mbrother2** [comment]
@bilalsaeed 
Did you run command `source /${HOME}/.profile `?

**Comment by bilalsaeed** [comment]
There's no .profile in the home. I am using Oracle Linux. Previously it was working fine but now we have upgraded our server machine the new installation does not work.

**Comment by mbrother2** [comment]
@bilalsaeed 

Please show the result of command `ls -al ${HOME}/bin`

**Comment by bilalsaeed** [comment]
I just resolved it now. Initially I installed on root user and I was running the command from oracle user. so I again installed it from oracle user and everything works now.

thank you for you help.
