### ISSUE TITLE
drive.exclude seems to be invalidated when SYNC_FILE=Yes

### ISSUE THREAD

**Issue by zengbs** [mbrother2/butdr#9]
Dear developers,

I found that `bash bin/cron_backup -v` will upload _all_ files, even if the files are already listed in `.config/accounts/drive.exclude` when `SYNC_FILE=Yes`. Am I correct? Thanks. :D

**Comment by mbrother2** [comment]
@zengbs 

You are right! When you use `SYNC_FILE=Yes`, this script will sync all your datas from local to cloud and can not exclude file.
